### ISSUE TITLE
0.5.1 not deployable due to recent master change

### ISSUE THREAD

**Issue by gokuatkai** [kubeflow/kubeflow#3433]
Hello, 
v0.5.1 uses master in aws utils.sh on the istio dependencies.
Thus it was removed throu: 
https://github.com/kubeflow/kubeflow/commit/f10f4fb954ad8617d0d6d35ba01356e4b19f3815
There is also a patch here:
https://github.com/kubeflow/kubeflow/commit/d38b6e7c02cf487d86f001269a971bd13b48d08c
But this last patch, I think should either:
- use the `KUBEFLOW_TAG` instead of `KUBEFLOW_VERSION`
- or add the letter `v` in front of `${KUBEFLOW_VERSION}`
Otherwise it wont find anything as the url is:
https://raw.githubusercontent.com/kubeflow/kubeflow/v0.5.1/dependencies/istio/install/crds.yaml
(containing the `v`)

Is there any chance to have v0.5.1 tag patched correctly?

**Comment by jlewi** [comment]
The code on the release branch should not depend on master; so that seems like a bug that we should fix.

/cc @Jeffwan

**Comment by Jeffwan** [comment]
@gokuatkai  I will ask my teammate to cherry-pick this change to 0.5-branch and then I will file a PR to update documentation to use stable branch.

**Comment by gokuatkai** [comment]
I tried to cherry pick this commit (https://github.com/kubeflow/kubeflow/commit/d38b6e7c02cf487d86f001269a971bd13b48d08c) but it fails, missing the letter `v`

**Comment by Jeffwan** [comment]
> I tried to cherry pick this commit ([d38b6e7](https://github.com/kubeflow/kubeflow/commit/d38b6e7c02cf487d86f001269a971bd13b48d08c)) but it fails, missing the letter `v`

Double check this issue. We need to use `KUBEFLOW_TAG` rather than `KUBEFLOW_VERSION` in the istio url.

**Comment by onur-sam-gtn-ai** [comment]
`scripts/aws/util.sh` is trying to reach the files in `dependencies/` but they no longer exist.
This applies both to the v0.5.1 (tries to download from master) and the master (tries to download from ${KUBEFLOW_TAG} which is again master).
There seems to be a problem with kiali (the required secret doesn't exist?) in v0.5.1 as well so even after hardcoding into util.sh, v0.5.1 is still not deployable.
I've only been able to deploy using commit 877a1a71bf317951bd0527db15f68d73c2e55c73.
https://github.com/kubeflow/kubeflow/commits/master/scripts/aws/util.sh

**Comment by Jeffwan** [comment]
@onur-sam-gtn-ai  

We cherry-pick change to https://github.com/kubeflow/kubeflow/pull/3444.

Then, if we use `v0.5-branch`, we are good to go.  It will get istio based on branch.

**Comment by Jeffwan** [comment]
@gokuatkai Please have another try and this issue should be fixed.

**Comment by onur-sam-gtn-ai** [comment]
I have just tried deploying v0.5-branch from fresh, it's still failing with kiali.
```Events:
  Type     Reason     Age                From                                                    Message
  ----     ------     ----               ----                                                    -------
  Normal   Scheduled  100s               default-scheduler                                       Successfully assigned istio-system/kiali-69d7f779c8-hw7sq to ip-192-168-180-228.eu-west-1.compute.internal
  Normal   Pulled     10s (x7 over 95s)  kubelet, ip-192-168-180-228.eu-west-1.compute.internal  Container image "docker.io/kiali/kiali:v0.12" already present on machine
  Warning  Failed     9s (x7 over 89s)   kubelet, ip-192-168-180-228.eu-west-1.compute.internal  Error: secrets "kiali" not found
[ec2-user@ip-172-31-0-107 ~]$ kubectl describe secret/kiali -n istio-system                                                                                                                                 
Error from server (NotFound): secrets "kiali" not found
```
Line 1542-1558 in dependencies/istio/install/istio-noauth.yaml at https://github.com/kubeflow/kubeflow/commit/47a28b7c42689444fdbf12901cbc98125d1908f9

I can also see that the master branch util.sh is still pointing to `dependencies/` that doesn't exist.

**Comment by Jeffwan** [comment]
> I have just tried deploying v0.5-branch from fresh, it's still failing with kiali.
> 
> ```
>   Type     Reason     Age                From                                                    Message
>   ----     ------     ----               ----                                                    -------
>   Normal   Scheduled  100s               default-scheduler                                       Successfully assigned istio-system/kiali-69d7f779c8-hw7sq to ip-192-168-180-228.eu-west-1.compute.internal
>   Normal   Pulled     10s (x7 over 95s)  kubelet, ip-192-168-180-228.eu-west-1.compute.internal  Container image "docker.io/kiali/kiali:v0.12" already present on machine
>   Warning  Failed     9s (x7 over 89s)   kubelet, ip-192-168-180-228.eu-west-1.compute.internal  Error: secrets "kiali" not found
> [ec2-user@ip-172-31-0-107 ~]$ kubectl describe secret/kiali -n istio-system                                                                                                                                 
> Error from server (NotFound): secrets "kiali" not found
> ```
> 
> This seems to be fixed at [47a28b7](https://github.com/kubeflow/kubeflow/commit/47a28b7c42689444fdbf12901cbc98125d1908f9)
> Line 1542-1558 in dependencies/istio/install/istio-noauth.yaml

Please manually create `kiali` secret in the cluster. 0.5-branch will use istio in 0.5-branch. This commit upgraded istio version and brings in new changes. It won't be cherry-picked back to cluster.

> I can also see that the master branch util.sh is still pointing to `dependencies/` that doesn't exist.
Yes. `util.sh` will be deprecated very soon. I am working on golang cli and that tool will not use istio under `dependencies`. Don't worry about the scripts now. Thanks! :D

**Comment by halayudha** [comment]
> > I have just tried deploying v0.5-branch from fresh, it's still failing with kiali.
> > ```
> >   Type     Reason     Age                From                                                    Message
> >   ----     ------     ----               ----                                                    -------
> >   Normal   Scheduled  100s               default-scheduler                                       Successfully assigned istio-system/kiali-69d7f779c8-hw7sq to ip-192-168-180-228.eu-west-1.compute.internal
> >   Normal   Pulled     10s (x7 over 95s)  kubelet, ip-192-168-180-228.eu-west-1.compute.internal  Container image "docker.io/kiali/kiali:v0.12" already present on machine
> >   Warning  Failed     9s (x7 over 89s)   kubelet, ip-192-168-180-228.eu-west-1.compute.internal  Error: secrets "kiali" not found
> > [ec2-user@ip-172-31-0-107 ~]$ kubectl describe secret/kiali -n istio-system                                                                                                                                 
> > Error from server (NotFound): secrets "kiali" not found
> > ```
> > 
> > 
> > This seems to be fixed at [47a28b7](https://github.com/kubeflow/kubeflow/commit/47a28b7c42689444fdbf12901cbc98125d1908f9)
> > Line 1542-1558 in dependencies/istio/install/istio-noauth.yaml
> 
> Please manually create `kiali` secret in the cluster. 0.5-branch will use istio in 0.5-branch. This commit upgraded istio version and brings in new changes. It won't be cherry-picked back to cluster.
> 
> > I can also see that the master branch util.sh is still pointing to `dependencies/` that doesn't exist.
> 
> Yes. `util.sh` will be deprecated very soon. I am working on golang cli and that tool will not use istio under `dependencies`. Don't worry about the scripts now. Thanks! :D

**Comment by halayudha** [comment]
> > I have just tried deploying v0.5-branch from fresh, it's still failing with kiali.
> > ```
> >   Type     Reason     Age                From                                                    Message
> >   ----     ------     ----               ----                                                    -------
> >   Normal   Scheduled  100s               default-scheduler                                       Successfully assigned istio-system/kiali-69d7f779c8-hw7sq to ip-192-168-180-228.eu-west-1.compute.internal
> >   Normal   Pulled     10s (x7 over 95s)  kubelet, ip-192-168-180-228.eu-west-1.compute.internal  Container image "docker.io/kiali/kiali:v0.12" already present on machine
> >   Warning  Failed     9s (x7 over 89s)   kubelet, ip-192-168-180-228.eu-west-1.compute.internal  Error: secrets "kiali" not found
> > [ec2-user@ip-172-31-0-107 ~]$ kubectl describe secret/kiali -n istio-system                                                                                                                                 
> > Error from server (NotFound): secrets "kiali" not found
> > ```
> > 
> > 
> > This seems to be fixed at [47a28b7](https://github.com/kubeflow/kubeflow/commit/47a28b7c42689444fdbf12901cbc98125d1908f9)
> > Line 1542-1558 in dependencies/istio/install/istio-noauth.yaml
> 
> Please manually create `kiali` secret in the cluster. 0.5-branch will use istio in 0.5-branch. This commit upgraded istio version and brings in new changes. It won't be cherry-picked back to cluster.

To manually create 'kiali' secret:
kubectl apply -f   , the content below:

apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
type: Opaque
data:
  username: YWRtaW4=   # admin
  passphrase: YWRtaW4= # admin
