### ISSUE TITLE
ml-pipelines [mysql] packets.go:36: unexpected EOF

### ISSUE THREAD

**Issue by marziman** [kubeflow/kubeflow#5540]
/kind bug

**What steps did you take and what happened:**

Helllo all, I think I need your help with this issue. We have installed KF1.2 on k8s 1.20 with kfctl and https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_istio_dex.v1.2.0.yaml
Everything works well, beside mysql and always get this error at the mysql pod.
I read/studied many possible solutions but none helped (e.g. switchin to Istio TLS to DISABLE). Same Problem like this colleague: https://stackoverflow.com/questions/65121700/kubeflow-ml-pipeline-cannot-connect-to-mysql-pod
kubectl -n kubeflow logs ml-pipeline-555747c844-mfqfk ml-pipeline-api-server
I0119 14:59:49.576535       6 client_manager.go:140] Initializing client manager
I0119 14:59:49.576735       6 config.go:56] Config DBConfig.ExtraParams not specified, skipping
[mysql] 2021/01/19 14:59:49 packets.go:36: unexpected EOF
[mysql] 2021/01/19 14:59:50 packets.go:36: unexpected EOF
[mysql] 2021/01/19 14:59:51 packets.go:36: unexpected EOF
[mysql] 2021/01/19 14:59:52 packets.go:36: unexpected EOF
[mysql] 2021/01/19 14:59:53 packets.go:36: unexpected EOF
[mysql] 2021/01/19 14:59:55 packets.go:36: unexpected EOF

**What did you expect to happen:**
Acessing the Pipelines without an Error in the UI. 

**Anything else you would like to add:**
The ml-pipeline pods are crashing, but this seems like a mysql/istio connection problem.

**Environment:**
Managed K8s

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- 1.2
- kfctl version: (use `kfctl version`):
- 1.2
- Kubernetes platform: (e.g. `minikube`)
- 1.20
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by DavidSpek** [comment]
/area pipelines

Just to be clear, is this an on-prem cluster running 1.20? What type of managed Kubernetes is it? I have been using Canonical's CDK 1.20 since just after the release on my on-prem cluster and haven't had this issue.

**Comment by marziman** [comment]
This is Kapsule K8s from Scaleway.

**Comment by DavidSpek** [comment]
I'm not sure changing the ml-pipelines-api-server image will work. Even upgrading KFP within a Kubeflow deployment is not yet to my knowledge.

**Comment by marziman** [comment]
For anyone finding this issue.
The problem is related to Istio 1.3, which needs to be configured properly to run mTLS with mysql.
Please look here, as it is described here: https://istio.io/v1.3/faq/security/#mysql-with-mtls

After apply authentication policies, the error was solved.
@jlewi FYI, this might be something that shall be highlighted in the KF docs. Giving a hint about the Istio version and it related troubleshooting could be helpful. cc @DavidSpek 

Closing the issue.

**Comment by ReggieCarey** [comment]
On Kubeflow 1.2.0 with Dex, Kubernetes Server 1.18.9.  I applied the above solution (Thanks @marziman) but the ml-pipeline process remains non-functional.  The errors prompting this issue are no longer present.  ML Pipeline logs reveal no obvious issues. Verified that mysql is up, can be pinged from ml-pipeline. 

Not sure what to do next.

**Comment by glotzerhotze** [comment]
We face the exact same issue. We are on Kubernetes 1.18.x - trying to install Kubeflow-1.2.0 with Dex. We did all the steps outlined above and we still can't get the ml-pipelines deployment to talk to the mysql-pod. Seems to be the same problem with the cache-server trying to talk to mysql. For both pods we see these messages in the logs - repeating all over again:

`
2021/03/01 07:51:35 Initing client manager....
[mysql] 2021/03/01 07:51:36 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:51:36 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:51:36 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:51:38 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:51:39 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:51:40 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:51:43 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:51:46 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:51:51 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:52:03 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:52:19 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:52:38 packets.go:36: unexpected EOF
`

`
I0301 07:52:31.106340       7 client_manager.go:134] Initializing client manager
I0301 07:52:31.106564       7 config.go:50] Config DBConfig.ExtraParams not specified, skipping
[mysql] 2021/03/01 07:52:31 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:52:31 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:52:32 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:52:33 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:52:35 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:52:38 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:52:42 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:52:48 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:52:58 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:53:12 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:53:35 packets.go:36: unexpected EOF
[mysql] 2021/03/01 07:53:57 packets.go:36: unexpected EOF
`

We can telnet into the mysql pod from the ml-pipeline pod, but still there seems to be a major problem preventing this to work at all.

**Comment by moficodes** [comment]
I am facing similar issue with Kubeflow 1.2 on OpenShift with istio 1.3. 

has there been any update or fixes available for this? 

@Tomcli

**Comment by maxisacoder** [comment]
istio 1.9 with kubeflow 1.3, still this error

**Comment by DavidSpek** [comment]
@maxisacoder I recommend creating an issue over at https://github.com/kubeflow/pipelines if you are having trouble with this.

**Comment by kim-sardine** [comment]
in my case, I solved it by restarting `mysql` deployment.
but still can't figure out why it happened.

https://github.com/go-sql-driver/mysql/issues/674 shows similar errors

**Comment by Shaked** [comment]
Do we know if https://github.com/kubeflow/pipelines/issues/5329 fixes this issue and if so how can we apply it to kubeflow 1.2 & 1.3?

**Comment by ReggieCarey** [comment]
I must sadly report this issue is raising its head on Kubeflow 1.3 installed on bare metal with the manifests approach (ArgoCD install would not work).  This is on a k8s that had KF 1.2 installed previously.

I wonder if left over artifacts from that distribution could be impacting KF 1.3.

```
Thu Jun 03 10:23:40 $ kubectl logs -n kubeflow ml-pipeline-6fd798d69b-mcmc8 ml-pipeline-api-server 
I0603 12:16:09.174530       6 client_manager.go:154] Initializing client manager
I0603 12:16:09.174619       6 config.go:57] Config DBConfig.ExtraParams not specified, skipping
[mysql] 2021/06/03 13:16:09 packets.go:36: unexpected EOF
[mysql] 2021/06/03 14:16:09 packets.go:36: unexpected EOF
```

**Comment by stobias123** [comment]
For others that find there way to this issue, I resolved with 
```bash
kubectl annotate deploy minio sidecar.istio.io/inject=false
kubectl annotate deploy mysql sidecar.istio.io/inject=false
```

**Comment by thesuperzapper** [comment]
For everyone watching, any time you see an error like `[mysql] XXXX/XX/XX XX:XX:XX packets.go:36: unexpected EOF` in the `cache-server` pods, you are almost certainly dealing with a network-level issue between your pods and the MySQL database.

The most likely case is that there is some __asymmetric routing__ going on. That is, your Pods might be able to create a connection to MySQL, but MySQL might not have a route back to your Pod. Note, [MySQL connections are complex](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase.html) and will sometimes initiate new TCP connections back to the client, which will fail in the previous case.

I have a more detailed write up on this issue: https://github.com/kubeflow/pipelines/issues/3763#issuecomment-1547009188

**Comment by rogeryuchao** [comment]
I suffered the same issue, actually, we I try to use exec to login the pod of ml-pipeline, I can use wget easily connect to mysql, so I am very curious why it still failed， I don't believe it is the connection related problems

**Comment by thesuperzapper** [comment]
Please read the comment in https://github.com/kubeflow/kubeflow/issues/5540#issuecomment-1547010022.

A simple `wget` is very different from how MySQL works.

**Comment by thesuperzapper** [comment]
@rogeryuchao Please read the comment in https://github.com/kubeflow/kubeflow/issues/5540#issuecomment-1547010022.

A simple `wget` is very different from how MySQL works.

**Comment by rogeryuchao** [comment]
Hi @Matew     Thank a lot for you comment. Actually I do several experiment to ensure this maybe not only the network issue~ Please check below evidence:1. Check cache server metadata writer, the DB connection is OK2. Check MySQL table schema, all schema is created, including the mlpipine part3. My installation is in another namespace, I have ensure all ConfigMap, destination rule, authorization, certificate, mutatingwebhook is rendered to fit for the new namespace4. I tried to use the original manifest to deploy in Kubeflow namespace, no such issue5. Next step I will try to deploy my specified manifest to Kubeflow namespace to see whether it is namespace related, I’m also reading the source code for mlpipeline-api-server, because the framework is large still under checkingBased on the evidences, I think it might be namespace or configuration related problems发自我的 iPhone在 2023年7月29日，05:15，Mathew Wicks ***@***.***> 写道：﻿
@rogeryuchao Please read the comment in #5540 (comment).
A simple wget is very different from how MySQL works.

**Comment by zoujuny** [comment]
> For others that find there way to this issue, I resolved with
> 
> ```shell
> kubectl annotate deploy minio sidecar.istio.io/inject=false
> kubectl annotate deploy mysql sidecar.istio.io/inject=false
> ```

@stobias123 This command is valid，the problem has been resolved. Thank you!
