### ISSUE TITLE
ERROR: After approving csr cache-server.kubeflow,

### ISSUE THREAD

**Issue by DomenicoCostantino** [kubeflow/kubeflow#6390]
Hi All,
I'm trying to install kubeflow using the installation with a "single command" (https://github.com/kubeflow/manifests#install-with-a-single-command ) but I'm always get stuck to the issue:

```
 echo 'ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.'
ERROR: After approving csr cache-server.kubeflow, the signed certificate did not appear on the resource. Giving up after 10 attempts.
+ exit 1
```
I'm using EKS cluster, I tried with 1.18, 1.19., 1.20 Kubernetes versions, but I obtain always the same result:

```
# kubectl -n kubeflow get pod
NAME                                                         READY   STATUS              RESTARTS   AGE
admission-webhook-deployment-587956b7f8-cphsq                1/1     Running             0          41m
application-controller-stateful-set-0                        1/1     Running             0          14m
cache-deployer-deployment-b5d47b4b-2662d                     1/2     CrashLoopBackOff    6          7m54s
cache-server-64d87df97d-mhrfs                                0/1     ContainerCreating   0          41m
centraldashboard-6d55488477-4gr5p                            1/1     Running             0          41m
jupyter-web-app-deployment-646ccd88db-sqkcc                  1/1     Running             0          41m
katib-controller-f8c7b4d6c-r7rxz                             1/1     Running             0          41m
katib-db-manager-54464cfc67-j7mbz                            1/1     Running             1          41m
katib-mysql-6dcb447c6f-qh2rp                                 1/1     Running             0          41m
katib-ui-9d89d8cd9-8jds9                                     1/1     Running             0          41m
kfserving-controller-manager-0                               2/2     Running             0          41m
kfserving-models-web-app-5d6cd6b5dd-ss454                    2/2     Running             0          39m
kubeflow-pipelines-profile-controller-df66bc7f4-w7s6c        1/1     Running             0          41m
metacontroller-0                                             1/1     Running             0          41m
metadata-envoy-deployment-799fcffc66-tr9rl                   1/1     Running             0          41m
metadata-grpc-deployment-6f6f7776c5-ncdjf                    1/1     Running             2          41m
metadata-writer-674f898649-86rrp                             1/1     Running             0          41m
minio-5b65df66c9-qnxsl                                       1/1     Running             0          41m
ml-pipeline-779b5c7f9-n9nh6                                  1/1     Running             1          41m
ml-pipeline-persistenceagent-9fcdd7cf5-f655d                 1/1     Running             0          41m
ml-pipeline-scheduledworkflow-687bb88644-blkvq               1/1     Running             0          41m
ml-pipeline-ui-97bc9468f-xntm6                               1/1     Running             0          41m
ml-pipeline-viewer-crd-984c8dc65-ghz7r                       1/1     Running             0          41m
ml-pipeline-visualizationserver-79c9c4dc86-7sv2l             1/1     Running             0          41m
mysql-f7b9b7dd4-4mjfd                                        1/1     Running             0          41m
notebook-controller-deployment-748684d476-8hkzc              1/1     Running             0          41m
profiles-deployment-7b66bd9fb5-2gqbf                         2/2     Running             0          41m
tensorboard-controller-controller-manager-866f4cd659-glq2w   2/2     Running             0          41m
tensorboards-web-app-deployment-85458976d4-265mc             1/1     Running             0          41m
training-operator-7b8cc9865d-6v6c7                           1/1     Running             0          41m
volumes-web-app-deployment-58f44749b9-9c56k                  1/1     Running             0          41m
workflow-controller-6bf87db995-d5xs9                         1/1     Running             0          41m
```

```
kustomize version
{Version:kustomize/v4.5.2 GitCommit:9091919699baf1c5a5bf71b32ca73a993e98088b BuildDate:2022-02-09T23:26:42Z GoOs:linux GoArch:amd64}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c49e2", GitCommit:"8c49e2efc3cfbb7788a58025e679787daed22018", GitTreeState:"clean", BuildDate:"2021-10-17T05:13:46Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

I don't understand how I have to fix this issue, could you support me?

**Comment by kimwnasptd** [comment]
Hi @DomenicoCostantino, we've also been tracking this for the KF 1.5 release https://github.com/kubeflow/manifests/issues/2146#issuecomment-1051361026

This should be fixed in the latest `1.8.0` KFP version

**Comment by ryansteakley** [comment]
@kimwnasptd I've tried the kf 1.5 release with both the 1.8.0 KFP version and the 1.8.1 KFP which is present in the -rc.2 tag. I'm still seeing this issue present when using Amazon eks similar to the user above.

**Comment by juliusvonkohout** [comment]
/close

There has been no activity for a long time. Please reopen if necessary.
